from sortdatastructures import *
insert= Insertion(list(map(int,input().split())))
print(insert.sort())
print("================")
# bubble= Bubble(list(map(int,input().split())))
# print(bubble.sort())
# print("=====================")
# quick= Quick()
# l=list(map(int,input().split()))
# high=len(l)
# print(quick.sort(l,0,high-1))
# merge=Merge()
# l=list(map(int,input().split()))
# high=len(l)
# print(merge.sort(l,0,high-1))
